In [2]:
import torch
import numpy as np

In [4]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [6]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [8]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [6]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

In [9]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.3538, 0.6149],
        [0.8535, 0.5190]])

In [10]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.0137, 0.1747, 0.1486],
        [0.1581, 0.8486, 0.2128]])

In [11]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
rand_tensor.shape

torch.Size([2, 3])

In [14]:
rand_tensor.dtype

torch.float32

In [15]:
rand_tensor.device

device(type='cpu')

In [16]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [17]:
 rand_tensor

tensor([[0.0137, 0.1747, 0.1486],
        [0.1581, 0.8486, 0.2128]])

In [18]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.0137, 1.0000, 0.1486],
        [0.1581, 1.0000, 0.2128]])

In [19]:
rand_tensor[0]

tensor([0.0137, 1.0000, 0.1486])

In [20]:
rand_tensor[:,0]

tensor([0.0137, 0.1581])

In [21]:
rand_tensor[...,-1]

tensor([0.1486, 0.2128])

In [22]:
rand_tensor.sum()

tensor(2.5332)

In [23]:
rand_tensor.sum().item()

2.533215284347534

In [24]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.0137, 1.0000, 0.1486, 0.0000, 0.0000, 0.0000],
        [0.1581, 1.0000, 0.2128, 0.0000, 0.0000, 0.0000]])

In [25]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.0137, 1.0000, 0.1486],
        [0.1581, 1.0000, 0.2128],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [26]:
rand_tensor.mul(ones_tensor)

tensor([[0.0137, 1.0000, 0.1486],
        [0.1581, 1.0000, 0.2128]])

In [27]:
rand_tensor.matmul(rand_tensor.T)

tensor([[1.0223, 1.0338],
        [1.0338, 1.0703]])

In [28]:
rand_tensor.add_(5)

tensor([[5.0137, 6.0000, 5.1486],
        [5.1581, 6.0000, 5.2128]])

In [29]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [30]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [31]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [32]:
x = torch.empty(1)
print(x)

tensor([3.5873e-43])


In [33]:
x.size()

torch.Size([1])

In [34]:
x = torch.empty(2,3)
print(x)

tensor([[5.0137, 6.0000, 5.1486],
        [5.1581, 6.0000, 5.2128]])


In [35]:
torch.empty(2,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [36]:
y=x.view(6)
y

tensor([5.0137, 6.0000, 5.1486, 5.1581, 6.0000, 5.2128])

In [37]:
z=x.view(1,-1)
z

tensor([[5.0137, 6.0000, 5.1486, 5.1581, 6.0000, 5.2128]])

In [38]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [39]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [40]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [41]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [42]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [43]:
a[1,1].item()

1.0

In [3]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])